### ISSUE TITLE
Regression test breaks if there is no workspace

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#64]
If a regression test folder does not contain a workspace file, the regression test break down.

This scenario could potentially be interesting when creating the test workspace from scratch every time using a python script.

```
15:56:17 Running test  16 (Enabled: 105, Total: 105) : fontrendering/fonts
15:56:17 Traceback (most recent call last):
15:56:17   File "../inviwo/tools/regression.py", line 211, in <module>
15:56:17     app.runTests(testrange = testrange, testfilter = testfilter, onlyRunFailed = args.failed)
15:56:17   File ".../inviwo/tools/ivwpy/regression/app.py", line 150, in runTests
15:56:17     report = self.runTest(test, run)
15:56:17   File ".../inviwo/tools/ivwpy/regression/app.py", line 98, in runTest
15:56:17     report = self.compareImages(test, report)
15:56:17   File ".../inviwo/tools/ivwpy/regression/app.py", line 172, in compareImages
15:56:17     outputdir = report['outputdir']
15:56:17 TypeError: 'NoneType' object is not subscriptable
```

**Comment by martinfalk** [comment]
In case the output argument `-o` is supplied to the regression script and the folder does not exist, the script fails as well (DataBase error).
