### ISSUE TITLE
clang-format.py sometimes fails due to branch already exists

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#752]
I think that L81 should be changed from `b=args.commit` to `B=args.commit` (capital `B`) since that force creating the branch if one with the name already axists. But I do not know what the value of `args.commit`. 

https://github.com/inviwo/inviwo/blob/673a067e883e8a70e35b3f71e8ed40f35993f9fe/tools/jenkins/check-format.py#L81

From [Jenkins log](http://jenkins.inviwo.org:8080/job/modules/job/PR-67/4/execution/node/39/log/)
```
20:35:24  + python3 ../inviwo/tools/jenkins/check-format.py --fix --commit feature/nanovgutils-rebase-3 --binary /usr/local/Cellar/llvm@6/6.0.1_1/bin/clang-format /Users/jenkins/jenkins/workspace/modules_PR-67/modules
20:35:25  clang-format version 6.0.1 (tags/RELEASE_601/final)
20:35:25  Fixing format, checking out: feature/nanovgutils-rebase-3
20:35:25  Traceback (most recent call last):
20:35:25    File "../inviwo/tools/jenkins/check-format.py", line 144, in <module>
20:35:25      main()
20:35:25    File "../inviwo/tools/jenkins/check-format.py", line 81, in main
20:35:25      localBranch = fref[0].ref.checkout(b=args.commit, track=True)
20:35:25    File "/usr/local/lib/python3.7/site-packages/git/refs/head.py", line 219, in checkout
20:35:25      self.repo.git.checkout(self, **kwargs)
20:35:25    File "/usr/local/lib/python3.7/site-packages/git/cmd.py", line 545, in <lambda>
20:35:25      return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
20:35:25    File "/usr/local/lib/python3.7/site-packages/git/cmd.py", line 1014, in _call_process
20:35:25      return self.execute(call, **exec_kwargs)
20:35:25    File "/usr/local/lib/python3.7/site-packages/git/cmd.py", line 825, in execute
20:35:25      raise GitCommandError(command, status, stderr_value, stdout_value)
20:35:25  git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
20:35:25    cmdline: git checkout -b feature/nanovgutils-rebase-3 --track origin/feature/nanovgutils-rebase-3
20:35:25    stderr: 'fatal: A branch named 'feature/nanovgutils-rebase-3' already exists.'
```

**Comment by r-englund** [comment]
I guess the problem is that we never delete the branch when an error occurs. Since we do a `sys.exit` 
https://github.com/inviwo/inviwo/blob/b55683e66d3b58d9e09f909309469ebaf2df2e86/tools/jenkins/check-format.py#L99-L115 
we will never reach the python code deleting the branch
https://github.com/inviwo/inviwo/blob/b55683e66d3b58d9e09f909309469ebaf2df2e86/tools/jenkins/check-format.py#L149
